### ISSUE TITLE
你好，来自坎巴拉智库的邀请

### ISSUE THREAD

**Issue by Acea-K** [1465114862/-#1]
你好这里是坎巴拉智库（Kerwis），目前最活跃的中国KSP mod制作组织。我们对你很有兴趣，现邀请加入我们的QQ群。
欢迎加入智库鸽笼，群聊号码：【数据删除】

**Comment by 1465114862** [comment]
问题回答不对，进不去_(´ཀ`」 ∠)__

**Comment by 1465114862** [comment]
其实用户名就是qq了，您方便的话可以拉下我。

**Comment by 1465114862** [comment]
进去了，可能手机出了点问题_(´ཀ`」 ∠)__
